services:
  nginx:
    build: .
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/www/certbot
      - ./conf/nginx.conf.template:/etc/nginx/nginx.conf.template
      - ./conf/conf.d:/etc/nginx/conf.d
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
      - ./conf/html:/etc/nginx/html
      - ./config.json:/etc/nginx/config.json
    command: /bin/sh -c "/entrypoint.sh & crond -f"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    networks:
      - shared-network

volumes:
  certbot-etc:
  certbot-var:

networks:
  shared-network:
    external: true

